config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#top'
  get "books" => "books#home"
  post "books" => "books#create"
  get "books/:id" => "books#show", as: "book"
  get "books/:id/edit" => "books#edit", as: "edit_book"
  patch "books/:id" => "books#update", as: "update_book"
  delete "books/:id" => "books#destroy", as: "delete_book"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def home
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created."
    else
      @books = Book.all
      render :home
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
       flash[:notice] = "Book was successfully updated."
    else
      render :edit
    end  
      
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

    private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<section class="edit">
  <h2>Editing Book</h2>
  <%= form_with model:@book, url: book_path(@book.id), local:true do |f| %>
  
  <% if @book.errors.any? %>
        <div class="error-box">
          <p class="error-text"><%= @book.errors.count %>errors prohibited this book from being saved:<p>
          <ul class="error-message">
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
  <label>Title</label>
  <%= f.text_field :title %>
  <label>Body</label>
  <%= f.text_area :body %>
  <div class="submit"><%= f.submit "Update Book" %></div>
  <% end %>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", books_path %>
</section>

app/views/books/home.html.erb
<div class="home">
  <section class="index">
    <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>title</th>
          <th>body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book_path(book.id) %></td>
          <td><%= link_to "Edit", edit_book_path(book.id) %></td>
          <td><%= link_to "Destroy", delete_book_path(book.id), method: :delete, "data-confirm" => "Are you shure?"  %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </section>

  <section class="new-book">
    <h2>New book</h2>
    <%= form_with model:@book, url: books_path, local:true do |f| %>

     <% if @book.errors.any? %>
        <div class="error-box">
          <p class="error-text"><%= @book.errors.count %>errors prohibited this book from being saved:<p>
          <ul class="error-message">
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <label>Title</label>
    <%= f.text_field :title %>
    <label>Body</label>
    <%= f.text_area :body %>
    <div class="submit"><%= f.submit "Create Book" %></div>
    <% end %>
  </section>
</div>

app/views/books/show.html.erb
<section class="show">

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

  </p>
  <p class="title"><strong>title</strong>:<%= @book.title %></p>
  <p class="body"><strong>body</strong>:<%= @book.body %></p>
  <%= link_to "Edit", edit_book_path(@book.id) %>
  <%= link_to "Back", books_path %>
</section>

app/views/books/top.html.erb
<section class="top">
  <h1>ようこそ Bookers へ！</h1>
  <p class="introduction"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
  <p class="introduction">印象を共有し交換することができます</p>
  <%= link_to "start", books_path, class: "start" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>